# Generated by Django 5.0.1 on 2024-03-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_madahyha_date_alter_madahyha_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='madahyha',
            name='date',
            field=models.DateField(),
        ),
    ]
