# Generated by Django 5.0.1 on 2024-03-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_madahyha_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='madahyha',
            name='date',
            field=models.TimeField(auto_now=True),
        ),
    ]
