# Generated by Django 5.0.1 on 2024-03-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_madahy_meno_sh_meno_v_delete_madahyha'),
    ]

    operations = [
        migrations.CreateModel(
            name='meno_shahadat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('esm_namayeshy', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='meno_veladat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('esm_namayeshy', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='meno_sh',
        ),
        migrations.DeleteModel(
            name='meno_v',
        ),
    ]
