# Generated by Django 5.0.1 on 2024-03-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_meno_shahadat_meno_veladat_delete_meno_sh_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='madahy1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daste', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('matn', models.TextField()),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='madahy',
        ),
    ]
